name: listvo
description: "Listvo é um aplicativo de organização criado para simplificar o gerenciamento das tarefas e lembretes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  timezone: ^0.9.2
  path_provider: ^2.0.12
  shared_preferences: ^2.0.15
  email_validator: ^2.0.1
  mask_text_input_formatter: ^2.9.0
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icone.png
    - assets/logo.png